### ISSUE TITLE
t/CallTrace/01_simple.t segfaults

### ISSUE THREAD

**Issue by eserte** [tokuhirom/B-Tap#7]
On some systems, t/CallTrace/01_simple.t fails with a segmentation fault:
```
    # $VAR1 = [
    #           [
    #             'expect(\\@p)->to_be([\'a\'])',
    #             '0'
    #           ],
    #           [
    #             'expect(\\@p)',
    #             'bless( {}, \'E\' )'
    #           ]
    #         ];
t/CallTrace/01_simple.t .. 
All 2 subtests passed 

Test Summary Report
-------------------
t/CallTrace/01_simple.t (Wstat: 139 Tests: 2 Failed: 0)
  Non-zero wait status: 139
  Parse errors: No plan found in TAP output
```
This happens on all of my perl 5.32.0 smokers, but also some other systems.

**Comment by tokuhirom** [comment]
i can't reproduce the issues. could you tell me the failing system information?

**Comment by eserte** [comment]
cpantesters seems to be available again --- you can find my reports at http://matrix.cpantesters.org/?dist=B-Tap;perl=5.32.0;reports=1 . Among the systems are Fedora 31, various Debians, CentOS 7 and FreeBSD 12.

Looking at http://matrix.cpantesters.org/?dist=B-Tap;os=linux;reports=1 there are also other perl versions affected, mainly from BINGOS' smokers.

**Comment by eserte** [comment]
Here's a backtrace --- unfortunately I don't have a perl with debugging symbols available:
```
#0  0x0000555828d5ad16 in Perl_op_free ()
#1  0x0000555828daf660 in Perl_cv_undef_flags ()
#2  0x0000555828e15068 in Perl_sv_clear ()
#3  0x0000555828e1562a in Perl_sv_free2 ()
#4  0x0000555828e41090 in Perl_leave_scope ()
#5  0x0000555828e0f7fe in Perl_pp_leavesub ()
#6  0x0000555828e06133 in Perl_runops_standard ()
#7  0x0000555828d7f0fc in perl_run ()
#8  0x0000555828d57292 in main ()
```

**Comment by eserte** [comment]
The most recent debugging perl I have is a perl 5.26.1 on debian:jessie. Here it's t/01_simple.t which fails with an assertion error --- maybe related?
```
$ perl5.26.1d -Mblib t/01_simple.t
ok 1
# B::Concise::compile(CODE(0x15bf3e8))
# 5  <1> leavesub[1 ref] K/REFC,1 ->(end)
# -     <@> lineseq KP ->5
# 1        <;> nextstate(main -771 01_simple.t:10) v:*,&,x*,x&,x$,$ ->2
# 4        <2> b_tap_tap sK/2 ->5
# 2           <$> const(IV 5963) s ->3
# 3           <$> b_tap_push_sv(IV \) l ->4
ok 2
perl5.26.1d: /opt/perl-5.26.1d/lib/5.26.1/x86_64-linux/CORE/inline.h:147: S_POPMARK: Assertion `(PL_markstack_ptr > PL_markstack) || !"MARK underflow"' failed.
[1]    17914 abort      perl5.26.1d -Mblib t/01_simple.t
```

**Comment by jkeenan** [comment]
t/CallTrace/01_simple.t still segfaults, now against perl-5.43.10.  See:
https://www.cpantesters.org/cpan/report/7d0c9e08-3cb4-11f1-bf0d-d141eeb8f5ab
